name: Test and Deploy Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Precommit Hooks
      run: |
        pre-commit run --all-files

    - name: Run tests with coverage
      run: |
        coverage run -m unittest tests.test_main.TestS3ValidationScript.test_validate_data
        coverage run -m unittest tests.test_main.TestS3ValidationScript.test_invalid_currency
        coverage run -m unittest tests.test_main.TestS3ValidationScript.test_null_values
        coverage run -m unittest tests.test_main.TestS3ValidationScript.test_invalid_timestamp
        coverage report

    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0

    - name: Initialize Terraform
      working-directory: terraform
      run: terraform init

    - name: Apply Terraform
      working-directory: terraform
      run: terraform apply -auto-approve
